### ISSUE TITLE
Test page throws errors

### ISSUE THREAD

**Issue by netzartist** [bljubisic/survey-md#2]
I cannot get a test page running based on the examples in the README.

I created `routes/+page.js` with:

```javascript
import md from '$lib/md.js';

/** @type {import('./$types').PageLoad} */
export async function load() {
  const text = "## Hi! Please pick a number.\n  (We shuffle them *every time*)\n\n?mynumber shuffle\n- 1337\n- [42](https://www.google.com/search?q=42)\n- 7±2\n\n@ mynumber\n[Submit](+)";
  const survey = await md(text);
  return {
    post: {
      title: `Title goes here`,
      content: survey,
    }
  };
}
```

and `routes/+page.svelte` containing:

```svelte
<script>
/** @type {import('./$types').PageData} */
export let data;
</script>

{@debug data}
```

In the dev server console I get 

- TypeError: Cannot read properties of undefined (reading 'prototype') at Function.survey (pointing to `src/lib/md.js`)
- Error: Cannot `parse` without `Parser` at assertParser (pointing to `node_modules/unified/index.js`)

Did I miss something? Could you check if you get the same error?

**Comment by bljubisic** [comment]
Yes, this happens because I have increased the version of Unified which is not working with current code for survey-md. I will fix this

**Comment by bljubisic** [comment]
Should be ok now

**Comment by netzartist** [comment]
Confirmed, errors are gone 🎉
